spring:
  profiles:
    active: local

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: false
    open-in-view: false

springdoc:
  swagger-ui:
    path: /docs/swagger
    url: /docs/openapi3.yaml
    disable-swagger-default-url: true
    persist-authorization: true
    display-request-duration: true
    default-model-expand-depth: 10
